export const mockData = [
  {
    id: 1,
    email: "john1@example.com",
    status: "Detected",
    date: "2023-11-01",
    risk: "High",
  },
  {
    id: 2,
    email: "john2@example.com",
    status: "Blocked",
    date: "2023-11-02",
    risk: "Medium",
  },
  {
    id: 3,
    email: "john3@example.com",
    status: "Quarantined",
    date: "2023-11-03",
    risk: "High",
  },
  {
    id: 4,
    email: "john4@example.com",
    status: "Detected",
    date: "2023-11-04",
    risk: "Low",
  },
  {
    id: 5,
    email: "john5@example.com",
    status: "Blocked",
    date: "2023-11-05",
    risk: "Medium",
  },
  {
    id: 6,
    email: "john6@example.com",
    status: "Quarantined",
    date: "2023-11-06",
    risk: "High",
  },
  {
    id: 7,
    email: "john7@example.com",
    status: "Detected",
    date: "2023-11-07",
    risk: "Low",
  },
  {
    id: 8,
    email: "john6@example.com",
    status: "Quarantined",
    date: "2023-11-06",
    risk: "High",
  },
  {
    id: 9,
    email: "john7@example.com",
    status: "Detected",
    date: "2023-11-07",
    risk: "Low",
  },
];
